version: '3'
services:
  api:
    container_name: garbage-pickup-api
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:8080"
    networks:
      - garbage-pickup-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://garbage-pickup-db:5432/garbage_pickup
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: garbage-pickup-db
    networks:
      - garbage-pickup-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=garbage_pickup
    ports:
      - 5432:5432
  storage:
    image: minio/minio
    container_name: garbage-pickup-storage
    networks:
      - garbage-pickup-network
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=miniouser
      - MINIO_ROOT_PASSWORD=miniouser
    volumes:
      - "/home/artix/.cache/garbage-pickup-storage:/files"
    entrypoint: "minio server /files --console-address ':9001'"
networks:
  garbage-pickup-network: { }