# for list of configuration read docs below
# - https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.web

spring:
# datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/garbage_pickup
    username: postgres
    password: postgres
  graphql:
    cors:
      allowed-headers: "*"
      allowed-methods: GET,POST
      allowed-origins: "*"
    graphiql:
      enabled: true
      path: /graphql/graphiql
    schema:
      file-extensions: .graphqls,.gqls,.graphql,.gql
      locations: classpath:graphql/**/
      printer: # if enable, schema is availabel unded graphql path + '/schema'
        enabled: false

