# for list of configuration read docs below
# - https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.web

spring:
  application:
    name: Garbage Pickup API
  # datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/garbage_pickup
    # url: jdbc:h2:mem://garbage_pickup
    username: postgres
    password: postgres
  graphql:
    path: /gql/graphql
    cors:
      allowed-headers: "*"
      allowed-methods: GET,POST
      allowed-origins: "*"
    graphiql:
      enabled: true
      path: /gql/graphiql
    schema:
      file-extensions: .graphqls,.gqls,.graphql,.gql
      locations: classpath:graphql/**/
      printer: # if enable, schema is availabel unded graphql path + '/schema'
        enabled: false
  jpa:
    hibernate:
      ddl-auto: update # set to "none" in production
    show-sql: false
    generate-ddl: true # set to false in production

# my custom configuration for jwt auth token
jwt:
  secret-key: mysecret
  token:
    expired-in:
      minute: 10080 # one week
